### ISSUE TITLE
Add homepage option

### ISSUE THREAD

**Issue by rivajunior** [tom-julux/parcel-plugin-sitemap#10]
I think would be nice to get, as a default option, the `homepage` key from `package.json`.
And then, if the user doesn't want this, he can set `sitemap.siteURL`.

That way keeps `package.json` cleaner.

**Comment by tom-julux** [comment]
I added this as a default and updated the npm package. The `homepage` key is used by [cra](https://github.com/facebook/create-react-app) and therefore widely used.

#### Additional information
I see this as more of a comfort option then a real feature. The `homepage` key is non-standard and therefore I will maybe drop this feature at some point. But as this is a breaking change I will bump the mayor version in the process.
